### ISSUE TITLE
MBID for GetSimilarAsync and GetInfoAsync

### ISSUE THREAD

**Issue by Walter5923** [avatar29A/Last.fm#11]
Hi,

Thank you very much for this great library. Could you please add a `mbid` parameter to _GetInfoAsync_, _GetSimilarAsync_, and _GetTopTagsAsync_?

`Task<Album> GetInfoAsync(string artist, string album, string mbid = null, bool autocorrect = true);`

The Last.fm API supports searching for `mbid`s. Thank you very much.

**Comment by wo80** [comment]
I've created a pull request that should fix the issue. Feel free to test the code or wait for the release.

The proposed API
```c#
Task<Album> GetInfoAsync(string artist, string album, string mbid = null, bool autocorrect = true);
```
isn't practical IMHO, since, when given a MBID, all other parameters are optional. So I've added separate methods like
```c#
Task<Album> GetInfoByMbidAsync(string mbid);
```
